apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  # namespace: orders
spec:
  replicas: 1  # Single pod (no scaling)
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: web
        image: weshigbee/examples-super-orders:2.2
        resources:
          requests:
            cpu: "500m" # == 1/2 vCPU (at least), so 60% of 500 = 300m is our scaling trigger
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  # namespace: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders
  # namespace: orders
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: superorders.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 3000

